Better MPI compiler unwrapping.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5256,15 +5256,9 @@ fi
 if test x$with_mpi_wrappers = xyes; then :
   MPICC="$CC"
 
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for base $MPICC compiler" >&5
-$as_echo_n "checking for base $MPICC compiler... " >&6; }
-if test "${ga_cv_mpicc_naked+set}" = set; then :
-  $as_echo_n "(cached) " >&6
-else
 
-versions="--version -v -V -qversion"
-inside="$srcdir/build-aux/inside.pl"
-case $MPICC in #(
+    wrapped="$CC"
+    case $wrapped in #(
   *_r) :
     compilers="bgxlc_r xlc_r" ;; #(
   *) :
@@ -5272,16 +5266,29 @@ case $MPICC in #(
   *) :
      ;;
 esac
-# Try separating stdout and stderr. Only compare stdout.
-if test "x$ga_cv_mpicc_naked" = x; then :
 
+
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for base $wrapped compiler" >&5
+$as_echo_n "checking for base $wrapped compiler... " >&6; }
+if test "${ga_cv_mpic_naked+set}" = set; then :
+  $as_echo_n "(cached) " >&6
+else
+
+versions="--version -v -V -qversion"
+inside="$srcdir/build-aux/inside.pl"
+found_wrapped_version=0
+# Try separating stdout and stderr. Only compare stdout.
+if test "x$ga_cv_mpic_naked" = x; then :
+
+echo "only comparing stdout" >&5
 for version in $versions; do
     for naked_compiler in $compilers; do
         rm -f mpi.txt mpi.err naked.txt naked.err
-        if $MPICC $version 1>mpi.txt 2>mpi.err; then :
-  if $naked_compiler $version 1>naked.txt 2>naked.err; then :
-  if $inside mpi.txt naked.txt; then :
-  ga_cv_mpicc_naked=$naked_compiler; break
+        if $wrapped $version 1>mpi.txt 2>mpi.err; then :
+  found_wrapped_version=1
+             if $naked_compiler $version 1>naked.txt 2>naked.err; then :
+  if $inside mpi.txt naked.txt >/dev/null; then :
+  ga_cv_mpic_naked=$naked_compiler; break
 else
   echo "inside.pl failed, skipping" >&5
 fi
@@ -5289,25 +5296,54 @@ else
   echo "$naked_compiler $version failed, skipping" >&5
 fi
 else
-  echo "$MPICC $version failed, skipping" >&5
+  echo "$wrapped $version failed, skipping" >&5
 fi
     done
-    if test "x$ga_cv_mpicc_naked" != x; then :
+    if test "x$ga_cv_mpic_naked" != x; then :
   break
 fi
 done
 
 fi
-if test "x$ga_cv_mpicc_naked" = x; then :
+# Perhaps none of the MPI compilers had a zero exit status (this is wrong).
+if test "x$found_wrapped_version" = x0; then :
 
+echo "no zero exit status found for MPI compilers" >&5
+if test "x$ga_cv_mpic_naked" = x; then :
+
+for version in $versions; do
+    for naked_compiler in $compilers; do
+        rm -f mpi.txt mpi.err naked.txt naked.err
+        $wrapped $version 1>mpi.txt 2>mpi.err
+        if $naked_compiler $version 1>naked.txt 2>naked.err; then :
+  if $inside mpi.txt naked.txt >/dev/null; then :
+  ga_cv_mpic_naked=$naked_compiler; break
+else
+  echo "inside.pl failed, skipping" >&5
+fi
+else
+  echo "$naked_compiler $version failed, skipping" >&5
+fi
+    done
+    if test "x$ga_cv_mpic_naked" != x; then :
+  break
+fi
+done
+
+fi
+
+fi
 # Try by combining stdout/err into one file.
+if test "x$ga_cv_mpic_naked" = x; then :
+
+echo "try combining stdout and stderr into one file" >&5
 for version in $versions; do
     for naked_compiler in $compilers; do
         rm -f mpi.txt naked.txt
-        if $MPICC $version 1>mpi.txt 2>&1; then :
+        if $wrapped $version 1>mpi.txt 2>&1; then :
   if $naked_compiler $version 1>naked.txt 2>&1; then :
-  if $inside mpi.txt naked.txt; then :
-  ga_cv_mpicc_naked=$naked_compiler; break
+  if $inside mpi.txt naked.txt >/dev/null; then :
+  ga_cv_mpic_naked=$naked_compiler; break
 else
   echo "inside.pl failed, skipping" >&5
 fi
@@ -5315,26 +5351,27 @@ else
   echo "$naked_compiler $version failed, skipping" >&5
 fi
 else
-  echo "$MPICC $version failed, skipping" >&5
+  echo "$wrapped $version failed, skipping" >&5
 fi
     done
-    if test "x$ga_cv_mpicc_naked" != x; then :
+    if test "x$ga_cv_mpic_naked" != x; then :
   break
 fi
 done
 
 fi
 rm -f mpi.txt mpi.err naked.txt naked.err
-if test "x$ga_cv_mpicc_naked" = x; then :
-  ga_cv_mpicc_naked=error
+if test "x$ga_cv_mpic_naked" = x; then :
+  ga_cv_mpic_naked=error
 fi
 
 fi
-{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ga_cv_mpicc_naked" >&5
-$as_echo "$ga_cv_mpicc_naked" >&6; }
-if test "x$ga_cv_mpicc_naked" = xerror; then :
-  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Could not determine the C compiler wrapped by MPI" >&5
-$as_echo "$as_me: WARNING: Could not determine the C compiler wrapped by MPI" >&2;}
+{ $as_echo "$as_me:${as_lineno-$LINENO}: result: $ga_cv_mpic_naked" >&5
+$as_echo "$ga_cv_mpic_naked" >&6; }
+
+if test "x$ga_cv_mpi_naked" = xerror; then :
+  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Could not determine the Fortran compiler wrapped by MPI" >&5
+$as_echo "$as_me: WARNING: Could not determine the Fortran compiler wrapped by MPI" >&2;}
      { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: This is usually okay" >&5
 $as_echo "$as_me: WARNING: This is usually okay" >&2;}
 fi
@@ -10960,15 +10997,9 @@ if test "x$enable_cxx" = xyes; then :
     if test x$with_mpi_wrappers = xyes; then :
   MPICXX="$CXX"
 
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for base $MPICXX compiler" >&5
-$as_echo_n "checking for base $MPICXX compiler... " >&6; }
-if test "${ga_cv_mpicxx_naked+set}" = set; then :
-  $as_echo_n "(cached) " >&6
-else
 
-versions="--version -v -V -qversion"
-inside="$srcdir/build-aux/inside.pl"
-case $MPICXX in #(
+    wrapped="$CXX"
+    case $wrapped in #(
   *_r) :
     compilers="bgxlC_r" ;; #(
   *) :
@@ -10976,14 +11007,27 @@ case $MPICXX in #(
   *) :
      ;;
 esac
+
+
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for base $wrapped compiler" >&5
+$as_echo_n "checking for base $wrapped compiler... " >&6; }
+if test "${ga_cv_mpicxx_naked+set}" = set; then :
+  $as_echo_n "(cached) " >&6
+else
+
+versions="--version -v -V -qversion"
+inside="$srcdir/build-aux/inside.pl"
+found_wrapped_version=0
 # Try separating stdout and stderr. Only compare stdout.
 if test "x$ga_cv_mpicxx_naked" = x; then :
 
+echo "only comparing stdout" >&5
 for version in $versions; do
     for naked_compiler in $compilers; do
         rm -f mpi.txt mpi.err naked.txt naked.err
-        if $MPICXX $version 1>mpi.txt 2>mpi.err; then :
-  if $naked_compiler $version 1>naked.txt 2>naked.err; then :
+        if $wrapped $version 1>mpi.txt 2>mpi.err; then :
+  found_wrapped_version=1
+             if $naked_compiler $version 1>naked.txt 2>naked.err; then :
   if $inside mpi.txt naked.txt >/dev/null; then :
   ga_cv_mpicxx_naked=$naked_compiler; break
 else
@@ -10993,7 +11037,7 @@ else
   echo "$naked_compiler $version failed, skipping" >&5
 fi
 else
-  echo "$MPICXX $version failed, skipping" >&5
+  echo "$wrapped $version failed, skipping" >&5
 fi
     done
     if test "x$ga_cv_mpicxx_naked" != x; then :
@@ -11002,13 +11046,42 @@ fi
 done
 
 fi
-# Try by combining stdout/err into one file.
+# Perhaps none of the MPI compilers had a zero exit status (this is wrong).
+if test "x$found_wrapped_version" = x0; then :
+
+echo "no zero exit status found for MPI compilers" >&5
 if test "x$ga_cv_mpicxx_naked" = x; then :
 
 for version in $versions; do
     for naked_compiler in $compilers; do
+        rm -f mpi.txt mpi.err naked.txt naked.err
+        $wrapped $version 1>mpi.txt 2>mpi.err
+        if $naked_compiler $version 1>naked.txt 2>naked.err; then :
+  if $inside mpi.txt naked.txt >/dev/null; then :
+  ga_cv_mpicxx_naked=$naked_compiler; break
+else
+  echo "inside.pl failed, skipping" >&5
+fi
+else
+  echo "$naked_compiler $version failed, skipping" >&5
+fi
+    done
+    if test "x$ga_cv_mpicxx_naked" != x; then :
+  break
+fi
+done
+
+fi
+
+fi
+# Try by combining stdout/err into one file.
+if test "x$ga_cv_mpicxx_naked" = x; then :
+
+echo "try combining stdout and stderr into one file" >&5
+for version in $versions; do
+    for naked_compiler in $compilers; do
         rm -f mpi.txt naked.txt
-        if $MPICXX $version 1>mpi.txt 2>&1; then :
+        if $wrapped $version 1>mpi.txt 2>&1; then :
   if $naked_compiler $version 1>naked.txt 2>&1; then :
   if $inside mpi.txt naked.txt >/dev/null; then :
   ga_cv_mpicxx_naked=$naked_compiler; break
@@ -11019,7 +11092,7 @@ else
   echo "$naked_compiler $version failed, skipping" >&5
 fi
 else
-  echo "$MPICXX $version failed, skipping" >&5
+  echo "$wrapped $version failed, skipping" >&5
 fi
     done
     if test "x$ga_cv_mpicxx_naked" != x; then :
@@ -11036,9 +11109,10 @@ fi
 fi
 { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ga_cv_mpicxx_naked" >&5
 $as_echo "$ga_cv_mpicxx_naked" >&6; }
-if test "x$ga_cv_mpicxx_naked" = xerror; then :
-  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Could not determine the C++ compiler wrapped by MPI" >&5
-$as_echo "$as_me: WARNING: Could not determine the C++ compiler wrapped by MPI" >&2;}
+
+if test "x$ga_cv_mpi_naked" = xerror; then :
+  { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Could not determine the Fortran compiler wrapped by MPI" >&5
+$as_echo "$as_me: WARNING: Could not determine the Fortran compiler wrapped by MPI" >&2;}
      { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: This is usually okay" >&5
 $as_echo "$as_me: WARNING: This is usually okay" >&2;}
 fi
@@ -11744,15 +11818,9 @@ ac_compiler_gnu=$ac_cv_f77_compiler_gnu
 if test x$with_mpi_wrappers = xyes; then :
   MPIF77="$F77"
 
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for base $MPIF77 compiler" >&5
-$as_echo_n "checking for base $MPIF77 compiler... " >&6; }
-if test "${ga_cv_mpif77_naked+set}" = set; then :
-  $as_echo_n "(cached) " >&6
-else
 
-versions="--version -v -V -qversion"
-inside="$srcdir/build-aux/inside.pl"
-case $MPIF77 in #(
+    wrapped="$F77"
+    case $wrapped in #(
   *_r) :
     compilers="bgxlf95_r xlf95_r bgxlf90_r xlf90_r bgxlf_r xlf_r" ;; #(
   *) :
@@ -11760,14 +11828,27 @@ case $MPIF77 in #(
   *) :
      ;;
 esac
+
+
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for base $wrapped compiler" >&5
+$as_echo_n "checking for base $wrapped compiler... " >&6; }
+if test "${ga_cv_mpif77_naked+set}" = set; then :
+  $as_echo_n "(cached) " >&6
+else
+
+versions="--version -v -V -qversion"
+inside="$srcdir/build-aux/inside.pl"
+found_wrapped_version=0
 # Try separating stdout and stderr. Only compare stdout.
 if test "x$ga_cv_mpif77_naked" = x; then :
 
+echo "only comparing stdout" >&5
 for version in $versions; do
     for naked_compiler in $compilers; do
         rm -f mpi.txt mpi.err naked.txt naked.err
-        if $MPIF77 $version 1>mpi.txt 2>mpi.err; then :
-  if $naked_compiler $version 1>naked.txt 2>naked.err; then :
+        if $wrapped $version 1>mpi.txt 2>mpi.err; then :
+  found_wrapped_version=1
+             if $naked_compiler $version 1>naked.txt 2>naked.err; then :
   if $inside mpi.txt naked.txt >/dev/null; then :
   ga_cv_mpif77_naked=$naked_compiler; break
 else
@@ -11777,7 +11858,7 @@ else
   echo "$naked_compiler $version failed, skipping" >&5
 fi
 else
-  echo "$MPIF77 $version failed, skipping" >&5
+  echo "$wrapped $version failed, skipping" >&5
 fi
     done
     if test "x$ga_cv_mpif77_naked" != x; then :
@@ -11786,13 +11867,42 @@ fi
 done
 
 fi
-# Try by combining stdout/err into one file.
+# Perhaps none of the MPI compilers had a zero exit status (this is wrong).
+if test "x$found_wrapped_version" = x0; then :
+
+echo "no zero exit status found for MPI compilers" >&5
 if test "x$ga_cv_mpif77_naked" = x; then :
 
 for version in $versions; do
     for naked_compiler in $compilers; do
+        rm -f mpi.txt mpi.err naked.txt naked.err
+        $wrapped $version 1>mpi.txt 2>mpi.err
+        if $naked_compiler $version 1>naked.txt 2>naked.err; then :
+  if $inside mpi.txt naked.txt >/dev/null; then :
+  ga_cv_mpif77_naked=$naked_compiler; break
+else
+  echo "inside.pl failed, skipping" >&5
+fi
+else
+  echo "$naked_compiler $version failed, skipping" >&5
+fi
+    done
+    if test "x$ga_cv_mpif77_naked" != x; then :
+  break
+fi
+done
+
+fi
+
+fi
+# Try by combining stdout/err into one file.
+if test "x$ga_cv_mpif77_naked" = x; then :
+
+echo "try combining stdout and stderr into one file" >&5
+for version in $versions; do
+    for naked_compiler in $compilers; do
         rm -f mpi.txt naked.txt
-        if $MPIF77 $version 1>mpi.txt 2>&1; then :
+        if $wrapped $version 1>mpi.txt 2>&1; then :
   if $naked_compiler $version 1>naked.txt 2>&1; then :
   if $inside mpi.txt naked.txt >/dev/null; then :
   ga_cv_mpif77_naked=$naked_compiler; break
@@ -11803,7 +11913,7 @@ else
   echo "$naked_compiler $version failed, skipping" >&5
 fi
 else
-  echo "$MPIF77 $version failed, skipping" >&5
+  echo "$wrapped $version failed, skipping" >&5
 fi
     done
     if test "x$ga_cv_mpif77_naked" != x; then :
@@ -11820,7 +11930,8 @@ fi
 fi
 { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ga_cv_mpif77_naked" >&5
 $as_echo "$ga_cv_mpif77_naked" >&6; }
-if test "x$ga_cv_mpif77_naked" = xerror; then :
+
+if test "x$ga_cv_mpi_naked" = xerror; then :
   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Could not determine the Fortran compiler wrapped by MPI" >&5
 $as_echo "$as_me: WARNING: Could not determine the Fortran compiler wrapped by MPI" >&2;}
      { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: This is usually okay" >&5
@@ -12205,19 +12316,24 @@ $as_echo "$ga_cv_f77_suppress" >&6; }
 
 
 if test "x$enable_f77" = xyes; then :
-  # temporarily restore unwrapped compilers
-     # this works around MPI libraries and paths getting into FLIBS
-     if test x$with_mpi_wrappers = xyes; then :
-  if test "x$ga_cv_mpicc_naked"  != xerror; then :
-  CC="$ga_cv_mpicc_naked"
+
+pagoda_mpi_unwrap_push_save_CC="$CC"
+pagoda_mpi_unwrap_push_save_CXX="$CXX"
+pagoda_mpi_unwrap_push_save_F77="$F77"
+pagoda_mpi_unwrap_push_save_FC="$FC"
+if test "x$ga_cv_mpic_naked"   != xerror; then :
+   CC="$ga_cv_mpic_naked"
 fi
-         if test "x$ga_cv_mpicxx_naked" != xerror; then :
+if test "x$ga_cv_mpicxx_naked" != xerror; then :
   CXX="$ga_cv_mpicxx_naked"
 fi
-         if test "x$ga_cv_mpif77_naked" != xerror; then :
+if test "x$ga_cv_mpif77_naked" != xerror; then :
   F77="$ga_cv_mpif77_naked"
 fi
+if test "x$ga_cv_mpifc_naked"  != xerror; then :
+   FC="$ga_cv_mpifc_naked"
 fi
+
      ac_ext=f
 ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
 ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
@@ -12524,12 +12640,12 @@ ac_compile='$F77 -c $FFLAGS conftest.$ac_ext >&5'
 ac_link='$F77 -o conftest$ac_exeext $FFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_f77_compiler_gnu
 
-     # and now that that's over, put the MPI compilers back
-     if test x$with_mpi_wrappers = xyes; then :
-  CC="$MPICC"
-         CXX="$MPICXX"
-         F77="$MPIF77"
-fi
+
+ CC="$pagoda_mpi_unwrap_push_save_CC"
+CXX="$pagoda_mpi_unwrap_push_save_CXX"
+F77="$pagoda_mpi_unwrap_push_save_F77"
+ FC="$pagoda_mpi_unwrap_push_save_FC"
+
      { $as_echo "$as_me:${as_lineno-$LINENO}: checking whether FLIBS needs -lgcc_s" >&5
 $as_echo_n "checking whether FLIBS needs -lgcc_s... " >&6; }
 if test "${ga_cv_flibs_gcc_s+set}" = set; then :
